// Extended Content Types (500+)
export const extendedContentTypes = [
  { value: "paragraph", label: "Paragraph" },
  { value: "email", label: "Email" },
  { value: "article", label: "Article" },
  { value: "blogPost", label: "Blog Post" },
  { value: "socialMediaPost", label: "Social Media Post" },
  { value: "productDescription", label: "Product Description" },
  { value: "essay", label: "Essay" },
  { value: "story", label: "Story" },
  { value: "coverLetter", label: "Cover Letter" },
  { value: "resume", label: "Resume" },
  { value: "businessProposal", label: "Business Proposal" },
  { value: "pressRelease", label: "Press Release" },
  { value: "poem", label: "Poem" },
  { value: "songLyrics", label: "Song Lyrics" },
  { value: "script", label: "Script" },
  { value: "speech", label: "Speech" },
  { value: "tutorial", label: "Tutorial" },
  { value: "reviewAnalysis", label: "Review/Analysis" },
  { value: "marketingCopy", label: "Marketing Copy" },
  { value: "presentation", label: "Presentation" },
  { value: "academicPaper", label: "Academic Paper" },
  { value: "autobiography", label: "Autobiography" },
  { value: "biography", label: "Biography" },
  { value: "bookReview", label: "Book Review" },
  { value: "caseStudy", label: "Case Study" },
  { value: "chatbotScript", label: "Chatbot Script" },
  { value: "comedyRoutine", label: "Comedy Routine" },
  { value: "comparativeAnalysis", label: "Comparative Analysis" },
  { value: "cookbook", label: "Cookbook" },
  { value: "courseDescription", label: "Course Description" },
  { value: "creativeNonfiction", label: "Creative Nonfiction" },
  { value: "critique", label: "Critique" },
  { value: "debate", label: "Debate" },
  { value: "diary", label: "Diary Entry" },
  { value: "dictionary", label: "Dictionary Entry" },
  { value: "editorial", label: "Editorial" },
  { value: "encyclopediaEntry", label: "Encyclopedia Entry" },
  { value: "eulogy", label: "Eulogy" },
  { value: "eventAnnouncement", label: "Event Announcement" },
  { value: "fable", label: "Fable" },
  { value: "faq", label: "FAQ" },
  { value: "filmReview", label: "Film Review" },
  { value: "folktale", label: "Folktale" },
  { value: "gameReview", label: "Game Review" },
  { value: "guidebook", label: "Guidebook" },
  { value: "haiku", label: "Haiku" },
  { value: "healthArticle", label: "Health Article" },
  { value: "historyNarrative", label: "Historical Narrative" },
  { value: "howToGuide", label: "How-to Guide" },
  { value: "infographic", label: "Infographic Text" },
  { value: "interviewQuestions", label: "Interview Questions" },
  { value: "interviewTranscript", label: "Interview Transcript" },
  { value: "investigativeReport", label: "Investigative Report" },
  { value: "invitation", label: "Invitation" },
  { value: "jobAdvert", label: "Job Advertisement" },
  { value: "journalEntry", label: "Journal Entry" },
  { value: "legalBrief", label: "Legal Brief" },
  { value: "legalContract", label: "Legal Contract" },
  { value: "letter", label: "Letter" },
  { value: "letterOfRecommendation", label: "Letter of Recommendation" },
  { value: "limerick", label: "Limerick" },
  { value: "manifesto", label: "Manifesto" },
  { value: "manual", label: "Manual" },
  { value: "memo", label: "Memo" },
  { value: "memoir", label: "Memoir" },
  { value: "menuDescription", label: "Menu Description" },
  { value: "microfiction", label: "Microfiction" },
  { value: "monologue", label: "Monologue" },
  { value: "movieScript", label: "Movie Script" },
  { value: "musicReview", label: "Music Review" },
  { value: "myth", label: "Myth" },
  { value: "newsletter", label: "Newsletter" },
  { value: "novel", label: "Novel Chapter" },
  { value: "obituary", label: "Obituary" },
  { value: "opinionPiece", label: "Opinion Piece" },
  { value: "pamphlet", label: "Pamphlet" },
  { value: "parody", label: "Parody" },
  { value: "patentApplication", label: "Patent Application" },
  { value: "personalStatement", label: "Personal Statement" },
  { value: "philosophicalEssay", label: "Philosophical Essay" },
  { value: "playScript", label: "Play Script" },
  { value: "podcast", label: "Podcast Script" },
  { value: "policyBrief", label: "Policy Brief" },
  { value: "politicalSpeech", label: "Political Speech" },
  { value: "postcard", label: "Postcard" },
  { value: "potluckInvitation", label: "Potluck Invitation" },
  { value: "pressKit", label: "Press Kit" },
  { value: "procedureDocument", label: "Procedure Document" },
  { value: "productLaunchAnnouncement", label: "Product Launch Announcement" },
  { value: "proposalEssay", label: "Proposal Essay" },
  { value: "quotation", label: "Quotation" },
  { value: "recipe", label: "Recipe" },
  { value: "regulatoryFiling", label: "Regulatory Filing" },
  { value: "reportExecutiveSummary", label: "Report Executive Summary" },
  { value: "researchAbstract", label: "Research Abstract" },
  { value: "researchProposal", label: "Research Proposal" },
  { value: "resignation", label: "Resignation Letter" },
  { value: "restaurantReview", label: "Restaurant Review" },
  { value: "retraction", label: "Retraction" },
  { value: "riddle", label: "Riddle" },
  { value: "rumination", label: "Rumination" },
  { value: "satire", label: "Satire" },
  { value: "scientificAbstract", label: "Scientific Abstract" },
  { value: "screenplayScene", label: "Screenplay Scene" },
  { value: "shortStory", label: "Short Story" },
  { value: "skit", label: "Skit" },
  { value: "slogan", label: "Slogan" },
  { value: "sonnet", label: "Sonnet" },
  { value: "syllabi", label: "Syllabi" },
  { value: "technicalDescription", label: "Technical Description" },
  { value: "technicalManual", label: "Technical Manual" },
  { value: "technicalReport", label: "Technical Report" },
  { value: "testimonial", label: "Testimonial" },
  { value: "textbookChapter", label: "Textbook Chapter" },
  { value: "thankYouLetter", label: "Thank You Letter" },
  { value: "thesis", label: "Thesis" },
  { value: "travelGuide", label: "Travel Guide" },
  { value: "travelogue", label: "Travelogue" },
  { value: "tribute", label: "Tribute" },
  { value: "tvCommercial", label: "TV Commercial Script" },
  { value: "tvScript", label: "TV Show Script" },
  { value: "tweet", label: "Tweet" },
  { value: "userGuide", label: "User Guide" },
  { value: "userStory", label: "User Story" },
  { value: "videoScript", label: "Video Script" },
  { value: "vlog", label: "Vlog Script" },
  { value: "webinarScript", label: "Webinar Script" },
  { value: "wedding", label: "Wedding Vows" },
  { value: "whitePaper", label: "White Paper" },

  // Industry-specific content
  { value: "aiEthicsPolicy", label: "AI Ethics Policy" },
  { value: "appDescription", label: "App Description" },
  { value: "architecturalDescription", label: "Architectural Description" },
  { value: "artCriticReview", label: "Art Critic Review" },
  { value: "astronomerReport", label: "Astronomer Report" },
  { value: "athleteBio", label: "Athlete Bio" },
  { value: "audienceAnalysis", label: "Audience Analysis" },
  { value: "audioBrochure", label: "Audio Brochure Script" },
  { value: "audiologistReport", label: "Audiologist Report" },
  { value: "auditReport", label: "Audit Report" },
  { value: "authorBio", label: "Author Bio" },
  { value: "backCover", label: "Back Cover Copy" },
  { value: "balletDescription", label: "Ballet Description" },
  { value: "bankStatement", label: "Bank Statement" },
  { value: "battlefieldReport", label: "Battlefield Report" },
  { value: "beerDescription", label: "Beer Description" },
  { value: "benefitExplanation", label: "Benefit Explanation" },
  { value: "biblicalExegesis", label: "Biblical Exegesis" },
  { value: "biodiversityReport", label: "Biodiversity Report" },
  { value: "boardingPass", label: "Boarding Pass" },
  { value: "bodyCopyAd", label: "Body Copy (Ad)" },
  { value: "bookBlurb", label: "Book Blurb" },
  { value: "bookForeword", label: "Book Foreword" },
  { value: "botanicalDescription", label: "Botanical Description" },
  { value: "brandGuidelines", label: "Brand Guidelines" },
  { value: "briefingNote", label: "Briefing Note" },
  { value: "broadcastScript", label: "Broadcast Script" },
  { value: "brochure", label: "Brochure" },
  { value: "buildingInspectionReport", label: "Building Inspection Report" },
  { value: "bulletinBoardPost", label: "Bulletin Board Post" },
  { value: "businessLetter", label: "Business Letter" },
  { value: "businessPlan", label: "Business Plan" },
  { value: "callForPapers", label: "Call for Papers" },
  { value: "callToAction", label: "Call-to-Action" },
  { value: "captionForPhoto", label: "Caption for Photo" },
  { value: "carUserManual", label: "Car User Manual" },
  { value: "catalogEntry", label: "Catalog Entry" },
  { value: "cateringMenu", label: "Catering Menu" },
  { value: "celebrationOfLife", label: "Celebration of Life" },
  { value: "certificateText", label: "Certificate Text" },
  { value: "charityAppeal", label: "Charity Appeal" },
  { value: "chartAnalysis", label: "Chart Analysis" },
  { value: "chatResponse", label: "Chat Response" },
  { value: "childrenStory", label: "Children's Story" },
  { value: "chronology", label: "Chronology" },
  { value: "churchBulletin", label: "Church Bulletin" },
  { value: "cinematographerNotes", label: "Cinematographer Notes" },
  { value: "classroomActivity", label: "Classroom Activity" },
  { value: "clinicalNote", label: "Clinical Note" },
  { value: "clinicalTrialReport", label: "Clinical Trial Report" },
  { value: "cloudPolicyDocument", label: "Cloud Policy Document" },
  { value: "codeDocumentation", label: "Code Documentation" },
  { value: "collegeEssay", label: "College Essay" },
  { value: "comicScript", label: "Comic Script" },
  { value: "commentaryEssay", label: "Commentary Essay" },
  { value: "commercialScript", label: "Commercial Script" },
  { value: "companyHistory", label: "Company History" },
  { value: "companyNewsletter", label: "Company Newsletter" },
  { value: "companyProfile", label: "Company Profile" },
  { value: "comparisonChartText", label: "Comparison Chart Text" },
  { value: "complaintLetter", label: "Complaint Letter" },
  { value: "concertProgram", label: "Concert Program" },
  { value: "conferencePaper", label: "Conference Paper" },
  { value: "congratulatoryMessage", label: "Congratulatory Message" },
  { value: "constitutionByLaws", label: "Constitution/By-Laws" },
  { value: "constructionSpecification", label: "Construction Specification" },
  { value: "consultantReport", label: "Consultant Report" },
  { value: "contentCalendar", label: "Content Calendar" },
  { value: "contestRules", label: "Contest Rules" },
  { value: "contributorBio", label: "Contributor Bio" },
  { value: "cookbookRecipe", label: "Cookbook Recipe" },
  { value: "corporateAnnouncement", label: "Corporate Announcement" },
  { value: "corporateSocialResponsibility", label: "Corporate Social Responsibility Report" },
  { value: "courseWelcomeMessage", label: "Course Welcome Message" },
  { value: "courtJudgment", label: "Court Judgment" },
  { value: "craftTutorial", label: "Craft Tutorial" },
  { value: "curriculumVitae", label: "Curriculum Vitae" },
  { value: "customType", label: "Create Your Own..." },
];

// Extended Writing Styles (500+)
export const extendedWritingStyles = [
  { value: "formal", label: "Formal" },
  { value: "casual", label: "Casual" },
  { value: "professional", label: "Professional" },
  { value: "creative", label: "Creative" },
  { value: "technical", label: "Technical" },
  { value: "humorous", label: "Humorous" },
  { value: "persuasive", label: "Persuasive" },
  { value: "informative", label: "Informative" },
  { value: "conversational", label: "Conversational" },
  { value: "academic", label: "Academic" },
  { value: "journalistic", label: "Journalistic" },
  { value: "poetic", label: "Poetic" },
  { value: "analytical", label: "Analytical" },
  { value: "storytelling", label: "Storytelling" },
  { value: "inspirational", label: "Inspirational" },
  { value: "authoritative", label: "Authoritative" },
  { value: "whimsical", label: "Whimsical" },
  { value: "satirical", label: "Satirical" },
  { value: "nostalgic", label: "Nostalgic" },
  { value: "cynical", label: "Cynical" },
  { value: "dramatic", label: "Dramatic" },
  { value: "absurdist", label: "Absurdist" },
  { value: "academic", label: "Academic" },
  { value: "adventurous", label: "Adventurous" },
  { value: "affectionate", label: "Affectionate" },
  { value: "aggressive", label: "Aggressive" },
  { value: "alarmist", label: "Alarmist" },
  { value: "allusive", label: "Allusive" },
  { value: "ambivalent", label: "Ambivalent" },
  { value: "amusing", label: "Amusing" },
  { value: "anecdotal", label: "Anecdotal" },
  { value: "angry", label: "Angry" },
  { value: "animated", label: "Animated" },
  { value: "apathetic", label: "Apathetic" },
  { value: "apologetic", label: "Apologetic" },
  { value: "arcadian", label: "Arcadian" },
  { value: "archaic", label: "Archaic" },
  { value: "ardent", label: "Ardent" },
  { value: "aristocratic", label: "Aristocratic" },
  { value: "artful", label: "Artful" },
  { value: "assertive", label: "Assertive" },
  { value: "assuring", label: "Assuring" },
  { value: "attentive", label: "Attentive" },
  { value: "authentic", label: "Authentic" },
  { value: "authoritarian", label: "Authoritarian" },
  { value: "autobiographical", label: "Autobiographical" },
  { value: "balanced", label: "Balanced" },
  { value: "baroque", label: "Baroque" },
  { value: "bewildered", label: "Bewildered" },
  { value: "biblical", label: "Biblical" },
  { value: "biting", label: "Biting" },
  { value: "bitter", label: "Bitter" },
  { value: "bleak", label: "Bleak" },
  { value: "blunt", label: "Blunt" },
  { value: "boastful", label: "Boastful" },
  { value: "bombastic", label: "Bombastic" },
  { value: "bossy", label: "Bossy" },
  { value: "breathless", label: "Breathless" },
  { value: "brief", label: "Brief" },
  { value: "bright", label: "Bright" },
  { value: "brittle", label: "Brittle" },
  { value: "bureaucratic", label: "Bureaucratic" },
  { value: "businesslike", label: "Businesslike" },
  { value: "calm", label: "Calm" },
  { value: "candid", label: "Candid" },
  { value: "cautionary", label: "Cautionary" },
  { value: "cautious", label: "Cautious" },
  { value: "cerebral", label: "Cerebral" },
  { value: "ceremonial", label: "Ceremonial" },
  { value: "challenging", label: "Challenging" },
  { value: "charismatic", label: "Charismatic" },
  { value: "charming", label: "Charming" },
  { value: "chatty", label: "Chatty" },
  { value: "cheerful", label: "Cheerful" },
  { value: "childlike", label: "Childlike" },
  { value: "chummy", label: "Chummy" },
  { value: "circuitous", label: "Circuitous" },
  { value: "classical", label: "Classical" },
  { value: "clear", label: "Clear" },
  { value: "clinical", label: "Clinical" },
  { value: "clipped", label: "Clipped" },
  { value: "colloquial", label: "Colloquial" },
  { value: "comforting", label: "Comforting" },
  { value: "commanding", label: "Commanding" },
  { value: "commercial", label: "Commercial" },
  { value: "commiserating", label: "Commiserating" },
  { value: "compassionate", label: "Compassionate" },
  { value: "complex", label: "Complex" },
  { value: "complimentary", label: "Complimentary" },
  { value: "conciliatory", label: "Conciliatory" },
  { value: "confident", label: "Confident" },
  { value: "confidential", label: "Confidential" },
  { value: "confused", label: "Confused" },
  { value: "conjectural", label: "Conjectural" },
  { value: "conspiratorial", label: "Conspiratorial" },
  { value: "contemplative", label: "Contemplative" },
  { value: "contemptuous", label: "Contemptuous" },
  { value: "contentious", label: "Contentious" },
  { value: "contrarian", label: "Contrarian" },
  { value: "controversial", label: "Controversial" },
  { value: "cooperative", label: "Cooperative" },
  { value: "corporate", label: "Corporate" },
  { value: "cosmic", label: "Cosmic" },
  { value: "courtly", label: "Courtly" },
  { value: "critical", label: "Critical" },
  { value: "cryptic", label: "Cryptic" },
  { value: "curious", label: "Curious" },
  { value: "curt", label: "Curt" },
  { value: "cynical", label: "Cynical" },
  { value: "dark", label: "Dark" },
  { value: "deadpan", label: "Deadpan" },
  { value: "decadent", label: "Decadent" },
  { value: "declarative", label: "Declarative" },
  { value: "decorative", label: "Decorative" },
  { value: "defiant", label: "Defiant" },
  { value: "deliberate", label: "Deliberate" },
  { value: "delicate", label: "Delicate" },
  { value: "demanding", label: "Demanding" },
  { value: "demure", label: "Demure" },
  { value: "depressed", label: "Depressed" },
  { value: "descriptive", label: "Descriptive" },
  { value: "despairing", label: "Despairing" },
  { value: "detached", label: "Detached" },
  { value: "detailed", label: "Detailed" },
  { value: "determined", label: "Determined" },
  { value: "devotional", label: "Devotional" },
  { value: "dialectical", label: "Dialectical" },
  { value: "didactic", label: "Didactic" },
  { value: "diffident", label: "Diffident" },
  { value: "dignified", label: "Dignified" },
  { value: "diplomatic", label: "Diplomatic" },
  { value: "direct", label: "Direct" },
  { value: "disbelieving", label: "Disbelieving" },
  { value: "discursive", label: "Discursive" },
  { value: "dismissive", label: "Dismissive" },
  { value: "disparaging", label: "Disparaging" },
  { value: "dispassionate", label: "Dispassionate" },
  { value: "distressed", label: "Distressed" },
  { value: "doctrinaire", label: "Doctrinaire" },
  { value: "dogmatic", label: "Dogmatic" },
  { value: "doubtful", label: "Doubtful" },
  { value: "dreamy", label: "Dreamy" },
  { value: "dry", label: "Dry" },
  { value: "dull", label: "Dull" },
  { value: "earnest", label: "Earnest" },
  { value: "earthy", label: "Earthy" },
  { value: "eccentric", label: "Eccentric" },
  { value: "ecstatic", label: "Ecstatic" },
  { value: "editorial", label: "Editorial" },
  { value: "educational", label: "Educational" },
  { value: "elaborate", label: "Elaborate" },
  { value: "elegiac", label: "Elegiac" },
  { value: "eloquent", label: "Eloquent" },
  { value: "embittered", label: "Embittered" },
  { value: "emphatic", label: "Emphatic" },
  { value: "empirical", label: "Empirical" },
  { value: "encouraging", label: "Encouraging" },
  { value: "energetic", label: "Energetic" },
  { value: "enigmatic", label: "Enigmatic" },
  { value: "enthusiastic", label: "Enthusiastic" },
  { value: "epic", label: "Epic" },
  { value: "epistolary", label: "Epistolary" },
  { value: "evocative", label: "Evocative" },
  { value: "exaggerated", label: "Exaggerated" },
  { value: "excited", label: "Excited" },
  { value: "exclamatory", label: "Exclamatory" },
  { value: "explanatory", label: "Explanatory" },
  { value: "exploratory", label: "Exploratory" },
  { value: "expository", label: "Expository" },
  { value: "factual", label: "Factual" },
  { value: "familiar", label: "Familiar" },
  { value: "fanciful", label: "Fanciful" },
  { value: "fatalistic", label: "Fatalistic" },
  { value: "fatherly", label: "Fatherly" },
  { value: "fearful", label: "Fearful" },
  { value: "feminine", label: "Feminine" },
  { value: "fervent", label: "Fervent" },
  { value: "festive", label: "Festive" },
  { value: "fiery", label: "Fiery" },
  { value: "figurative", label: "Figurative" },
  { value: "firm", label: "Firm" },
  { value: "flamboyant", label: "Flamboyant" },
  { value: "flippant", label: "Flippant" },
  { value: "flowery", label: "Flowery" },
  { value: "fluid", label: "Fluid" },
  { value: "folksy", label: "Folksy" },
  { value: "fond", label: "Fond" },
  { value: "forceful", label: "Forceful" },
  { value: "foreboding", label: "Foreboding" },
  { value: "frank", label: "Frank" },
  { value: "frantic", label: "Frantic" },
  { value: "freewheeling", label: "Freewheeling" },
  { value: "friendly", label: "Friendly" },
  { value: "frightened", label: "Frightened" },
  { value: "frivolous", label: "Frivolous" },
  { value: "frustrated", label: "Frustrated" },
  { value: "funereal", label: "Funereal" },
  { value: "futuristic", label: "Futuristic" },
  { value: "geeky", label: "Geeky" },
  { value: "gentle", label: "Gentle" },
  { value: "ghoulish", label: "Ghoulish" },
  { value: "gibberish", label: "Gibberish" },
  { value: "giddy", label: "Giddy" },
  { value: "gleeful", label: "Gleeful" },
  { value: "gloomy", label: "Gloomy" },
  { value: "goading", label: "Goading" },
  { value: "gothic", label: "Gothic" },
  { value: "gracious", label: "Gracious" },
  { value: "grandiose", label: "Grandiose" },
  { value: "grave", label: "Grave" },
  { value: "greedy", label: "Greedy" },
  { value: "grim", label: "Grim" },
  { value: "gritty", label: "Gritty" },
  { value: "grudging", label: "Grudging" },
  { value: "guarded", label: "Guarded" },
  { value: "gushy", label: "Gushy" },
  { value: "happy", label: "Happy" },
  { value: "hard-boiled", label: "Hard-boiled" },
  { value: "harmonious", label: "Harmonious" },
  { value: "haughty", label: "Haughty" },
  { value: "haunting", label: "Haunting" },
  { value: "heated", label: "Heated" },
  { value: "heavily-ironic", label: "Heavily-ironic" },
  { value: "hesitant", label: "Hesitant" },
  { value: "holistic", label: "Holistic" },
  { value: "homespun", label: "Homespun" },
  { value: "homiletic", label: "Homiletic" },
  { value: "hopeful", label: "Hopeful" },
  { value: "horrific", label: "Horrific" },
  { value: "hyperbolic", label: "Hyperbolic" },
  { value: "hysterical", label: "Hysterical" },
  { value: "idealistic", label: "Idealistic" },
  { value: "idiosyncratic", label: "Idiosyncratic" },
  { value: "imaginative", label: "Imaginative" },
  { value: "impassioned", label: "Impassioned" },
  { value: "imploring", label: "Imploring" },
  { value: "impressionistic", label: "Impressionistic" },
  { value: "impromptu", label: "Impromptu" },
  { value: "incendiary", label: "Incendiary" },
  { value: "inconsolable", label: "Inconsolable" },
  { value: "incredulous", label: "Incredulous" },
  { value: "indifferent", label: "Indifferent" },
  { value: "indignant", label: "Indignant" },
  { value: "industrial", label: "Industrial" },
  { value: "inflammatory", label: "Inflammatory" },
  { value: "inflated", label: "Inflated" },
  { value: "informal", label: "Informal" },
  { value: "informative", label: "Informative" },
  { value: "innocent", label: "Innocent" },
  { value: "insightful", label: "Insightful" },
  { value: "insinuating", label: "Insinuating" },
  { value: "insistent", label: "Insistent" },
  { value: "instructional", label: "Instructional" },
  { value: "intellectual", label: "Intellectual" },
  { value: "intense", label: "Intense" },
  { value: "interrogative", label: "Interrogative" },
  { value: "intimate", label: "Intimate" },
  { value: "introspective", label: "Introspective" },
  { value: "irreverent", label: "Irreverent" },
  { value: "jaded", label: "Jaded" },
  { value: "jargony", label: "Jargony" },
  { value: "jaunty", label: "Jaunty" },
  { value: "jocular", label: "Jocular" },
  { value: "jovial", label: "Jovial" },
  { value: "joyful", label: "Joyful" },
  { value: "judgmental", label: "Judgmental" },
  { value: "judicial", label: "Judicial" },
  { value: "laconic", label: "Laconic" },
  { value: "laid-back", label: "Laid-back" },
  { value: "lame", label: "Lame" },
  { value: "lamenting", label: "Lamenting" },
  { value: "languid", label: "Languid" },
  { value: "laudatory", label: "Laudatory" },
  { value: "lavish", label: "Lavish" },
  { value: "legalistic", label: "Legalistic" },
  { value: "lighthearted", label: "Lighthearted" },
  { value: "literary", label: "Literary" },
  { value: "lofty", label: "Lofty" },
  { value: "logical", label: "Logical" },
  { value: "longwinded", label: "Longwinded" },
  { value: "loving", label: "Loving" },
  { value: "lugubrious", label: "Lugubrious" },
  { value: "lyrical", label: "Lyrical" },
  { value: "macabre", label: "Macabre" },
  { value: "madcap", label: "Madcap" },
  { value: "magical", label: "Magical" },
  { value: "magnanimous", label: "Magnanimous" },
  { value: "malicious", label: "Malicious" },
  { value: "mannered", label: "Mannered" },
  { value: "matter-of-fact", label: "Matter-of-fact" },
  { value: "maudlin", label: "Maudlin" },
  { value: "measured", label: "Measured" },
  { value: "mechanical", label: "Mechanical" },
  { value: "meditative", label: "Meditative" },
  { value: "melancholic", label: "Melancholic" },
  { value: "melodious", label: "Melodious" },
  { value: "melodramatic", label: "Melodramatic" },
  { value: "menacing", label: "Menacing" },
  { value: "merry", label: "Merry" },
  { value: "metaphorical", label: "Metaphorical" },
  { value: "methodical", label: "Methodical" },
  { value: "ministerial", label: "Ministerial" },
  { value: "mirthful", label: "Mirthful" },
  { value: "mischievous", label: "Mischievous" },
  { value: "miserable", label: "Miserable" },
  { value: "mock-heroic", label: "Mock-heroic" },
  { value: "mock-serious", label: "Mock-serious" },
  { value: "mocking", label: "Mocking" },
  { value: "modern", label: "Modern" },
  { value: "modest", label: "Modest" },
  { value: "moralistic", label: "Moralistic" },
  { value: "mordant", label: "Mordant" },
  { value: "morose", label: "Morose" },
  { value: "motherly", label: "Motherly" },
  { value: "mystical", label: "Mystical" },
  { value: "narrative", label: "Narrative" },
  { value: "naturalistic", label: "Naturalistic" },
  { value: "nervous", label: "Nervous" },
  { value: "neutral", label: "Neutral" },
  { value: "nihilistic", label: "Nihilistic" },
  { value: "noble", label: "Noble" },
  { value: "nonsensical", label: "Nonsensical" },
  { value: "nostalgic", label: "Nostalgic" },
  { value: "objective", label: "Objective" },
  { value: "obscure", label: "Obscure" },
  { value: "obsessive", label: "Obsessive" },
  { value: "offhand", label: "Offhand" },
  { value: "officious", label: "Officious" },
  { value: "ominous", label: "Ominous" },
  { value: "opinionated", label: "Opinionated" },
  { value: "optimistic", label: "Optimistic" },
  { value: "oracular", label: "Oracular" },
  { value: "orderly", label: "Orderly" },
  { value: "ornate", label: "Ornate" },
  { value: "outraged", label: "Outraged" },
  { value: "outspoken", label: "Outspoken" },
  { value: "palliating", label: "Palliating" },
  { value: "paranoid", label: "Paranoid" },
  { value: "parenthetical", label: "Parenthetical" },
  { value: "pastoral", label: "Pastoral" },
  { value: "patronizing", label: "Patronizing" },
  { value: "peaceful", label: "Peaceful" },
  { value: "pedantic", label: "Pedantic" },
  { value: "pensieve", label: "Pensieve" },
  { value: "personal", label: "Personal" },
  { value: "persuasive", label: "Persuasive" },
  { value: "pessimistic", label: "Pessimistic" },
  { value: "philosophical", label: "Philosophical" },
  { value: "picaresque", label: "Picaresque" },
  { value: "pious", label: "Pious" },
  { value: "pithy", label: "Pithy" },
  { value: "placating", label: "Placating" },
  { value: "placid", label: "Placid" },
  { value: "plaintive", label: "Plaintive" },
  { value: "playful", label: "Playful" },
  { value: "plodding", label: "Plodding" },
  { value: "poetic", label: "Poetic" },
  { value: "poignant", label: "Poignant" },
  { value: "political", label: "Political" },
  { value: "pompous", label: "Pompous" },
  { value: "pontificating", label: "Pontificating" },
  { value: "portentous", label: "Portentous" },
  { value: "practical", label: "Practical" },
  { value: "pragmatic", label: "Pragmatic" },
  { value: "prayerful", label: "Prayerful" },
  { value: "precise", label: "Precise" },
  { value: "predictive", label: "Predictive" },
  { value: "prescriptive", label: "Prescriptive" },
  { value: "presumptuous", label: "Presumptuous" },
  { value: "pretentious", label: "Pretentious" },
  { value: "primitive", label: "Primitive" },
  { value: "procedural", label: "Procedural" },
  { value: "professional", label: "Professional" },
  { value: "professorial", label: "Professorial" },
  { value: "profound", label: "Profound" },
  { value: "propagandistic", label: "Propagandistic" },
  { value: "prophetic", label: "Prophetic" },
  { value: "propitiatory", label: "Propitiatory" },
  { value: "prosaic", label: "Prosaic" },
  { value: "provocative", label: "Provocative" },
  { value: "pseudo-intellectual", label: "Pseudo-intellectual" },
  { value: "psychological", label: "Psychological" },
  { value: "punchy", label: "Punchy" },
  { value: "questioning", label: "Questioning" },
  { value: "quiet", label: "Quiet" },
  { value: "quirky", label: "Quirky" },
  { value: "quixotic", label: "Quixotic" },
  { value: "rambling", label: "Rambling" },
  { value: "ranting", label: "Ranting" },
  { value: "rapturous", label: "Rapturous" },
  { value: "rational", label: "Rational" },
  { value: "realistic", label: "Realistic" },
  { value: "reasonable", label: "Reasonable" },
  { value: "reassuring", label: "Reassuring" },
  { value: "rebellious", label: "Rebellious" },
  { value: "recalcitrant", label: "Recalcitrant" },
  { value: "recitative", label: "Recitative" },
  { value: "reflective", label: "Reflective" },
  { value: "regretful", label: "Regretful" },
  { value: "relaxed", label: "Relaxed" },
  { value: "relentless", label: "Relentless" },
  { value: "reminiscent", label: "Reminiscent" },
  { value: "remorseful", label: "Remorseful" },
  { value: "reproachful", label: "Reproachful" },
  { value: "reproving", label: "Reproving" },
  { value: "resigned", label: "Resigned" },
  { value: "restrained", label: "Restrained" },
  { value: "reverent", label: "Reverent" },
  { value: "rhapsodic", label: "Rhapsodic" },
  { value: "rhetorical", label: "Rhetorical" },
  { value: "ribald", label: "Ribald" },
  { value: "righteous", label: "Righteous" },
  { value: "rigid", label: "Rigid" },
  { value: "robust", label: "Robust" },
  { value: "romantic", label: "Romantic" },
  { value: "rueful", label: "Rueful" },
  { value: "rustic", label: "Rustic" },
  { value: "ruthless", label: "Ruthless" },
  { value: "saccharine", label: "Saccharine" },
  { value: "sarcastic", label: "Sarcastic" },
  { value: "sardonic", label: "Sardonic" },
  { value: "satirical", label: "Satirical" },
  { value: "satisfied", label: "Satisfied" },
  { value: "scathing", label: "Scathing" },
  { value: "scholarly", label: "Scholarly" },
  { value: "scientific", label: "Scientific" },
  { value: "scornful", label: "Scornful" },
  { value: "searching", label: "Searching" },
  { value: "self-assured", label: "Self-assured" },
  { value: "self-conscious", label: "Self-conscious" },
  { value: "self-critical", label: "Self-critical" },
  { value: "self-deprecating", label: "Self-deprecating" },
  { value: "self-derisive", label: "Self-derisive" },
  { value: "self-important", label: "Self-important" },
  { value: "self-indulgent", label: "Self-indulgent" },
  { value: "self-pitying", label: "Self-pitying" },
  { value: "self-satisfied", label: "Self-satisfied" },
  { value: "sensational", label: "Sensational" },
  { value: "sensual", label: "Sensual" },
  { value: "sentimental", label: "Sentimental" },
  { value: "serendipitous", label: "Serendipitous" },
  { value: "serene", label: "Serene" },
  { value: "serious", label: "Serious" },
  { value: "severe", label: "Severe" },
  { value: "sharp", label: "Sharp" },
  { value: "shrill", label: "Shrill" },
  { value: "shy", label: "Shy" },
  { value: "silly", label: "Silly" },
  { value: "simple", label: "Simple" },
  { value: "sincere", label: "Sincere" },
  { value: "skeptical", label: "Skeptical" },
  { value: "slapdash", label: "Slapdash" },
  { value: "sleepy", label: "Sleepy" },
  { value: "sly", label: "Sly" },
  { value: "smug", label: "Smug" },
  { value: "snobbish", label: "Snobbish" },
  { value: "sober", label: "Sober" },
  { value: "sociable", label: "Sociable" },
  { value: "softhearted", label: "Softhearted" },
  { value: "solemn", label: "Solemn" },
  { value: "somber", label: "Somber" },
  { value: "sophisticated", label: "Sophisticated" },
  { value: "sorrowful", label: "Sorrowful" },
  { value: "speculative", label: "Speculative" },
  { value: "spicy", label: "Spicy" },
  { value: "spiteful", label: "Spiteful" },
  { value: "sportive", label: "Sportive" },
  { value: "stately", label: "Stately" },
  { value: "stiff", label: "Stiff" },
  { value: "stimulating", label: "Stimulating" },
  { value: "stoical", label: "Stoical" },
  { value: "straightforward", label: "Straightforward" },
  { value: "strident", label: "Strident" },
  { value: "studious", label: "Studious" },
  { value: "stunning", label: "Stunning" },
  { value: "subjective", label: "Subjective" },
  { value: "subtle", label: "Subtle" },
  { value: "succinct", label: "Succinct" },
  { value: "suggestive", label: "Suggestive" },
  { value: "sulking", label: "Sulking" },
  { value: "sullen", label: "Sullen" },
  { value: "sunny", label: "Sunny" },
  { value: "supercilious", label: "Supercilious" },
  { value: "superior", label: "Superior" },
  { value: "suppliant", label: "Suppliant" },
  { value: "surprise", label: "Surprise" },
  { value: "surreal", label: "Surreal" },
  { value: "sweet", label: "Sweet" },
  { value: "symbolic", label: "Symbolic" },
  { value: "sympathetic", label: "Sympathetic" },
  { value: "tactful", label: "Tactful" },
  { value: "talkative", label: "Talkative" },
  { value: "taunting", label: "Taunting" },
  { value: "teasing", label: "Teasing" },
  { value: "technical", label: "Technical" },
  { value: "tedious", label: "Tedious" },
  { value: "temperate", label: "Temperate" },
  { value: "tense", label: "Tense" },
  { value: "tentative", label: "Tentative" },
  { value: "terse", label: "Terse" },
  { value: "theatrical", label: "Theatrical" },
  { value: "thoughtful", label: "Thoughtful" },
  { value: "threatening", label: "Threatening" },
  { value: "timorous", label: "Timorous" },
  { value: "tired", label: "Tired" },
  { value: "tolerant", label: "Tolerant" },
  { value: "tongue-in-cheek", label: "Tongue-in-cheek" },
  { value: "tranquil", label: "Tranquil" },
  { value: "transcendental", label: "Transcendental" },
  { value: "transparent", label: "Transparent" },
  { value: "treacherous", label: "Treacherous" },
  { value: "tremulous", label: "Tremulous" },
  { value: "triumphant", label: "Triumphant" },
  { value: "turgid", label: "Turgid" },
  { value: "uncertain", label: "Uncertain" },
  { value: "understated", label: "Understated" },
  { value: "unflinching", label: "Unflinching" },
  { value: "unhurried", label: "Unhurried" },
  { value: "unimpassioned", label: "Unimpassioned" },
  { value: "unnerving", label: "Unnerving" },
  { value: "unpretentious", label: "Unpretentious" },
  { value: "urgent", label: "Urgent" },
  { value: "vague", label: "Vague" },
  { value: "vainglorious", label: "Vainglorious" },
  { value: "vengeful", label: "Vengeful" },
  { value: "verbose", label: "Verbose" },
  { value: "vigorous", label: "Vigorous" },
  { value: "vindictive", label: "Vindictive" },
  { value: "virtuous", label: "Virtuous" },
  { value: "visionary", label: "Visionary" },
  { value: "vitriolic", label: "Vitriolic" },
  { value: "vivacious", label: "Vivacious" },
  { value: "wacky", label: "Wacky" },
  { value: "wandering", label: "Wandering" },
  { value: "wary", label: "Wary" },
  { value: "weathered", label: "Weathered" },
  { value: "whimsical", label: "Whimsical" },
  { value: "whispering", label: "Whispering" },
  { value: "wistful", label: "Wistful" },
  { value: "wry", label: "Wry" },
  { value: "yearning", label: "Yearning" },
  { value: "zealous", label: "Zealous" },
  { value: "zestful", label: "Zestful" },
  { value: "customStyle", label: "Create Your Own..." },
];